### ISSUE TITLE
Cannot use mustaches in an elements tagname: `{{tagName` at L3:C5

### ISSUE THREAD

**Issue by ahlivehr** [akshay-kr/ember-scroll-to-target#2]
I installed the plugin and when starting Ember I get the following error:
Error: Cannot use mustaches in an elements tagname: `{{tagName` at L3:C5):

I have no other changes other than what was installed with this plugin.

**Comment by ahlivehr** [comment]
I believe this is where the error comes from: https://github.com/glimmerjs/glimmer-vm/blob/master/packages/%40glimmer/syntax/lib/parser/handlebars-node-visitors.ts#L119. Looks like it has to do with glimmer not allowing mustaches in tag names. The line where this fails in this repo is here: https://github.com/akshay-kr/ember-scroll-to-target/blob/master/addon/templates/components/scroll-to.hbs#L3.

` <{{tagName}}>{{label}}</{{tagName}}>`

**Comment by akshay-kr** [comment]
I was able to produce the error on updating `ember-cli` version. I have updated the addon to use `tagName` property as you suggested. I have also released a new version `v0.1.0` with the fix. Can you please try installing the new version and verify that this issue is fixed?
