### ISSUE TITLE
Component is not updated after updating offset

### ISSUE THREAD

**Issue by petervtzand** [akshay-kr/ember-scroll-to-target#4]
In my use case, I must first calculate the offset on my page, due to some fixed elements. This value is then passed to the scroll-to component like this:
```hbs
{{scroll-to
  target=(concat "#student-id-" feedbackData_.studentId)
  tagName="a"
  classNames=(local-class "scroll-to-student")
  label=feedbackData_.studentFullName
  duration=500
  offset=scrollOffset}}
```

But this doesn't work, I guess because the component is already rendered. I have a workaround for it:
```hbs
{{#if scrollOffset}}
  {{scroll-to
    target=(concat "#student-id-" feedbackData_.studentId)
    tagName="a"
    classNames=(local-class "scroll-to-student")
    label=feedbackData_.studentFullName
    duration=500
    offset=scrollOffset}}
{{/if}}
```

But that seems kinda hacky. It would be nicer if the component would update when the offset is updated (or another attribute like `label`?)

**Comment by akshay-kr** [comment]
Fixed in version `ember-scroll-to-target@1.0.1`
